name: Bug Report
description: Report a bug or unexpected behavior
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear description of the bug
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Initialize Aurum with {{config}}...
        2. Call connect()...
        3. See error
    validations:
      required: true
  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      placeholder: '0.1.0'
    validations:
      required: true
  - type: dropdown
    id: wallet
    attributes:
      label: Wallet
      description: Which wallet(s) were you using when the issue occurred?
      options:
        - MetaMask
        - Coinbase Wallet
        - Phantom
        - Rabby
        - WalletConnect
        - Reown AppKit
        - Email
        - Ledger
        - Brave
        - All/Multiple
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile (iOS)
        - Mobile (Android)
        - Other
