name: Bug Report
description: Report a bug or unexpected behavior
labels: ['bug']
body:
  - type: textarea
    id: bug-report
    attributes:
      label: Bug Report
      description: |
        **Describe the bug**
        A clear description of the bug

        **Steps to reproduce**
        1. Initialize Aurum with {{config}}...
        2. Call connect()...
        3. See error

        **SDK Version**
        e.g. 0.1.0

        **Wallet**
        Which wallet(s) were you using? (MetaMask, Coinbase Wallet, Phantom, Rabby, WalletConnect, Email, Brave)

        **Browser**
        Chrome, Firefox, Safari, Edge, Mobile (iOS/Android), Other
    validations:
      required: true
